name: Deploy Api Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, linux, x64]

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # 프로젝트 Node 버전

      - name: Install dependencies
        run: npm ci

      - name: Stop and start application with PM2
        run: |
          pm2 delete app || true
          pm2 start npm --name app -- start
